//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetStoreAppConsole.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLocalization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetStoreAppConsole.Strings.StringLocalization", typeof(StringLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Get the Store app (console) version: {0} 的本地化字符串。
        /// </summary>
        internal static string HeaderDescription1 {
            get {
                return ResourceManager.GetString("HeaderDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get the Store app (console program) to quickly query and download the installation package for Microsoft Store apps. 的本地化字符串。
        /// </summary>
        internal static string HeaderDescription2 {
            get {
                return ResourceManager.GetString("HeaderDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For more information, navigate to the &quot;About&quot; page of the application and learn about it in the &quot;Usage Instructions&quot; module. 的本地化字符串。
        /// </summary>
        internal static string HeaderDescription3 {
            get {
                return ResourceManager.GetString("HeaderDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetStoreApp (Dev) 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current console program is under development and is currently only used as a placeholder. 的本地化字符串。
        /// </summary>
        internal static string UnfinishedNotification1 {
            get {
                return ResourceManager.GetString("UnfinishedNotification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The program redirects to the desktop app. 的本地化字符串。
        /// </summary>
        internal static string UnfinishedNotification2 {
            get {
                return ResourceManager.GetString("UnfinishedNotification2", resourceCulture);
            }
        }
    }
}
