using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Messaging;
using GetStoreApp.Messages;
using GetStoreApp.Models;
using GetStoreApp.Services.Settings;
using HtmlAgilityPack;
using System;
using System.Collections.Generic;
using System.Linq;

namespace GetStoreApp.Services.Home
{
    /// <summary>
    /// 解析HtmlRequestService生成的列表数据
    /// Parse the list data generated by htmlRequestService
    /// </summary>
    public class HtmlParseService : ObservableRecipient, IDisposable
    {
        private HtmlDocument HtmlDocument { get; set; }

        /// <summary>
        /// 初始化HtmlParseService类时添加HtmlReqeustService生成的字符串数据
        /// The HtmlParseService class is initialized with string data generated by the HtmlReqeustService
        /// </summary>
        /// <param name="HttpRequestData">HtmlReqeustService生成的数据</param>
        public HtmlParseService(HttpRequestDataModel HttpRequestData)
        {
            HtmlDocument = new HtmlDocument();

            // 添加网页请求返回的具体内容
            HtmlDocument.LoadHtml(HttpRequestData.RequestContent);
        }

        /// <summary>
        /// 类在结束使用后准备回收时注销消息接收
        /// The class receives an unregister message when it is ready for recycling after it is finished in use
        /// </summary>
        public void Dispose()
        {
            Messenger.UnregisterAll(this);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// 检查服务器返回的内容是空列表还是带有具体内容的信息
        /// Checks whether the content returned by the server is an empty list or information with specific content
        /// </summary>
        /// <returns>得到带有数据的信息，返回False，没有得到带有数据的信息，返回True</returns>
        public bool IsSuccessfulRequest()
        {
            // 加载带有返回结果状态的标签
            HtmlNode RequestStateNode = HtmlDocument.DocumentNode.SelectSingleNode("//p");

            // 加载带有返回结果的文本信息
            string ReqeustContext = RequestStateNode.InnerText;

            // 服务器获取到正确的信息，此时返回为False，如果返回其他信息，返回True
            return Convert.ToBoolean(string.Compare(ReqeustContext, "The links were successfully received from the Microsoft Store server."));
        }

        /// <summary>
        /// 解析网页数据中包含的CategoryID信息
        /// Parse the CategoryID information contained in the web page data
        /// </summary>
        /// <returns>返回得到的CategoryID字符串数据</returns>
        public string HtmlParseCID()
        {
            return HtmlDocument.DocumentNode.SelectSingleNode("//i").InnerText;
        }

        /// <summary>
        /// 解析网页数据中包含的所有信息
        /// Parse all the information contained in the web page data
        /// </summary>
        /// <returns>返回得到的所有所有标签数据</returns>
        public List<ResultDataModel> HtmlParseLinks()
        {
            List<ResultDataModel> ResultDataList = new();

            // 获取<table class="tftable" border="1" align="center">标签信息
            HtmlNode RequestLinkNode = HtmlDocument.DocumentNode.SelectSingleNode("//table[@class='tftable' and @border='1' and @align='center']");

            // 获取<table class="tftable" border="1" align="center">下所有的tr标签
            IEnumerable<HtmlNode> RequestLinkNodeList = RequestLinkNode
                 .Descendants("tr")
                 .Where(x => x.Attributes.Contains("style"));

            foreach (var item in RequestLinkNodeList)
            {
                // 访问每一个tr标签的所有td标签，td标签包括应用包名称，链接名称，链接过期时间，应用包文件SHA-1值，应用包文件大小
                HtmlNodeCollection TdNodeList = item.ChildNodes;

                // 应用包名称
                string AppPackageName = TdNodeList[0].InnerText;

                // 链接名称
                string AppLink = TdNodeList[0].SelectSingleNode("a").Attributes["href"].Value;

                // 链接过期时间
                string AppLinkExpireTime = TdNodeList[1].InnerText;

                // 应用包文件SHA-1值
                string AppSHA1 = TdNodeList[2].InnerText;

                // 应用包文件大小
                string AppPackageSize = TdNodeList[3].InnerText;

                // 将获取到的数据添加到ResultDataList集合中
                ResultDataList.Add(new ResultDataModel(AppPackageName, AppLink, AppLinkExpireTime, AppSHA1, AppPackageSize));
            }

            return ResultDataList;
        }
    }
}
