//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetStoreApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GetStoreApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///	&lt;Header&gt;
        ///		&lt;Action d3p1:mustUnderstand=&quot;1&quot; xmlns:d3p1=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetCookie&lt;/Action&gt;
        ///		&lt;MessageID xmlns=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;urn:uuid:b9b43757-2247-4d7b-ae8f-a71ba8a22386&lt;/MessageID&gt;
        ///		&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string cookie {
            get {
                return ResourceManager.GetString("cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Lengths {
            get {
                object obj = ResourceManager.GetObject("Lengths", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] LICENSE {
            get {
                object obj = ResourceManager.GetObject("LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] MileAria2 {
            get {
                object obj = ResourceManager.GetObject("MileAria2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Have you forgot to initialize app&apos;s resources? 的本地化字符串。
        /// </summary>
        public static string ResourcesInitializeFailed {
            get {
                return ResourceManager.GetString("ResourcesInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;s:Envelope
        ///	xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;
        ///	xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///	&lt;s:Header&gt;
        ///		&lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetExtendedUpdateInfo2&lt;/a:Action&gt;
        ///		&lt;a:MessageID&gt;urn:uuid:2cc99c2e-3b3e-4fb1-9e31-0cd30e6f43a0&lt;/a:MessageID&gt;
        ///		&lt;a:To s:mustUnderstand=&quot;1&quot;&gt;https://fe3.delivery.mp.microsoft.com/ClientWebService/client.asmx/secured&lt;/a:To&gt;
        ///		&lt;o:Security s:mustUnderstand=&quot;1&quot;
        ///			xmlns:o=&quot;http://doc [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;s:Envelope
        ///	xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;
        ///	xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///	&lt;s:Header&gt;
        ///		&lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/SyncUpdates&lt;/a:Action&gt;
        ///		&lt;a:MessageID&gt;urn:uuid:175df68c-4b91-41ee-b70b-f2208c65438e&lt;/a:MessageID&gt;
        ///		&lt;a:To s:mustUnderstand=&quot;1&quot;&gt;https://fe3.delivery.mp.microsoft.com/ClientWebService/client.asmx&lt;/a:To&gt;
        ///		&lt;o:Security s:mustUnderstand=&quot;1&quot;
        ///			xmlns:o=&quot;http://docs.oasis-open.org/ws [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string wu {
            get {
                return ResourceManager.GetString("wu", resourceCulture);
            }
        }
    }
}
